name: "ruff format checking"

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master" , "development" ]

jobs:
  lint:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Ruff format checking
      uses: astral-sh/ruff-action@v2
      with:
        args: "format --check"
        src: "./simopt"
